# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/dominik/Downloads/clion-2019.2.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/dominik/Downloads/clion-2019.2.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/dominik/CLionProjects/AgeOfWar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/dominik/CLionProjects/AgeOfWar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/dominik/Downloads/clion-2019.2.3/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/dominik/Downloads/clion-2019.2.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominik/CLionProjects/AgeOfWar/CMakeFiles /home/dominik/CLionProjects/AgeOfWar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/dominik/CLionProjects/AgeOfWar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AgeOfWar

# Build rule for target.
AgeOfWar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AgeOfWar
.PHONY : AgeOfWar

# fast build rule for target.
AgeOfWar/fast:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/build
.PHONY : AgeOfWar/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/main.cpp.s
.PHONY : main.cpp.s

src/game/Board.o: src/game/Board.cpp.o

.PHONY : src/game/Board.o

# target to build an object file
src/game/Board.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/Board.cpp.o
.PHONY : src/game/Board.cpp.o

src/game/Board.i: src/game/Board.cpp.i

.PHONY : src/game/Board.i

# target to preprocess a source file
src/game/Board.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/Board.cpp.i
.PHONY : src/game/Board.cpp.i

src/game/Board.s: src/game/Board.cpp.s

.PHONY : src/game/Board.s

# target to generate assembly for a file
src/game/Board.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/Board.cpp.s
.PHONY : src/game/Board.cpp.s

src/game/BuyingManager.o: src/game/BuyingManager.cpp.o

.PHONY : src/game/BuyingManager.o

# target to build an object file
src/game/BuyingManager.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/BuyingManager.cpp.o
.PHONY : src/game/BuyingManager.cpp.o

src/game/BuyingManager.i: src/game/BuyingManager.cpp.i

.PHONY : src/game/BuyingManager.i

# target to preprocess a source file
src/game/BuyingManager.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/BuyingManager.cpp.i
.PHONY : src/game/BuyingManager.cpp.i

src/game/BuyingManager.s: src/game/BuyingManager.cpp.s

.PHONY : src/game/BuyingManager.s

# target to generate assembly for a file
src/game/BuyingManager.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/BuyingManager.cpp.s
.PHONY : src/game/BuyingManager.cpp.s

src/game/GameLogger.o: src/game/GameLogger.cpp.o

.PHONY : src/game/GameLogger.o

# target to build an object file
src/game/GameLogger.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/GameLogger.cpp.o
.PHONY : src/game/GameLogger.cpp.o

src/game/GameLogger.i: src/game/GameLogger.cpp.i

.PHONY : src/game/GameLogger.i

# target to preprocess a source file
src/game/GameLogger.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/GameLogger.cpp.i
.PHONY : src/game/GameLogger.cpp.i

src/game/GameLogger.s: src/game/GameLogger.cpp.s

.PHONY : src/game/GameLogger.s

# target to generate assembly for a file
src/game/GameLogger.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/GameLogger.cpp.s
.PHONY : src/game/GameLogger.cpp.s

src/game/GameManager.o: src/game/GameManager.cpp.o

.PHONY : src/game/GameManager.o

# target to build an object file
src/game/GameManager.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/GameManager.cpp.o
.PHONY : src/game/GameManager.cpp.o

src/game/GameManager.i: src/game/GameManager.cpp.i

.PHONY : src/game/GameManager.i

# target to preprocess a source file
src/game/GameManager.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/GameManager.cpp.i
.PHONY : src/game/GameManager.cpp.i

src/game/GameManager.s: src/game/GameManager.cpp.s

.PHONY : src/game/GameManager.s

# target to generate assembly for a file
src/game/GameManager.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/game/GameManager.cpp.s
.PHONY : src/game/GameManager.cpp.s

src/players/ComputerPlayer.o: src/players/ComputerPlayer.cpp.o

.PHONY : src/players/ComputerPlayer.o

# target to build an object file
src/players/ComputerPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/ComputerPlayer.cpp.o
.PHONY : src/players/ComputerPlayer.cpp.o

src/players/ComputerPlayer.i: src/players/ComputerPlayer.cpp.i

.PHONY : src/players/ComputerPlayer.i

# target to preprocess a source file
src/players/ComputerPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/ComputerPlayer.cpp.i
.PHONY : src/players/ComputerPlayer.cpp.i

src/players/ComputerPlayer.s: src/players/ComputerPlayer.cpp.s

.PHONY : src/players/ComputerPlayer.s

# target to generate assembly for a file
src/players/ComputerPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/ComputerPlayer.cpp.s
.PHONY : src/players/ComputerPlayer.cpp.s

src/players/HumanPlayer.o: src/players/HumanPlayer.cpp.o

.PHONY : src/players/HumanPlayer.o

# target to build an object file
src/players/HumanPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/HumanPlayer.cpp.o
.PHONY : src/players/HumanPlayer.cpp.o

src/players/HumanPlayer.i: src/players/HumanPlayer.cpp.i

.PHONY : src/players/HumanPlayer.i

# target to preprocess a source file
src/players/HumanPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/HumanPlayer.cpp.i
.PHONY : src/players/HumanPlayer.cpp.i

src/players/HumanPlayer.s: src/players/HumanPlayer.cpp.s

.PHONY : src/players/HumanPlayer.s

# target to generate assembly for a file
src/players/HumanPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/HumanPlayer.cpp.s
.PHONY : src/players/HumanPlayer.cpp.s

src/players/IPlayer.o: src/players/IPlayer.cpp.o

.PHONY : src/players/IPlayer.o

# target to build an object file
src/players/IPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/IPlayer.cpp.o
.PHONY : src/players/IPlayer.cpp.o

src/players/IPlayer.i: src/players/IPlayer.cpp.i

.PHONY : src/players/IPlayer.i

# target to preprocess a source file
src/players/IPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/IPlayer.cpp.i
.PHONY : src/players/IPlayer.cpp.i

src/players/IPlayer.s: src/players/IPlayer.cpp.s

.PHONY : src/players/IPlayer.s

# target to generate assembly for a file
src/players/IPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/players/IPlayer.cpp.s
.PHONY : src/players/IPlayer.cpp.s

src/units/Archer.o: src/units/Archer.cpp.o

.PHONY : src/units/Archer.o

# target to build an object file
src/units/Archer.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Archer.cpp.o
.PHONY : src/units/Archer.cpp.o

src/units/Archer.i: src/units/Archer.cpp.i

.PHONY : src/units/Archer.i

# target to preprocess a source file
src/units/Archer.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Archer.cpp.i
.PHONY : src/units/Archer.cpp.i

src/units/Archer.s: src/units/Archer.cpp.s

.PHONY : src/units/Archer.s

# target to generate assembly for a file
src/units/Archer.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Archer.cpp.s
.PHONY : src/units/Archer.cpp.s

src/units/Catapult.o: src/units/Catapult.cpp.o

.PHONY : src/units/Catapult.o

# target to build an object file
src/units/Catapult.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Catapult.cpp.o
.PHONY : src/units/Catapult.cpp.o

src/units/Catapult.i: src/units/Catapult.cpp.i

.PHONY : src/units/Catapult.i

# target to preprocess a source file
src/units/Catapult.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Catapult.cpp.i
.PHONY : src/units/Catapult.cpp.i

src/units/Catapult.s: src/units/Catapult.cpp.s

.PHONY : src/units/Catapult.s

# target to generate assembly for a file
src/units/Catapult.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Catapult.cpp.s
.PHONY : src/units/Catapult.cpp.s

src/units/Fantassin.o: src/units/Fantassin.cpp.o

.PHONY : src/units/Fantassin.o

# target to build an object file
src/units/Fantassin.cpp.o:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Fantassin.cpp.o
.PHONY : src/units/Fantassin.cpp.o

src/units/Fantassin.i: src/units/Fantassin.cpp.i

.PHONY : src/units/Fantassin.i

# target to preprocess a source file
src/units/Fantassin.cpp.i:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Fantassin.cpp.i
.PHONY : src/units/Fantassin.cpp.i

src/units/Fantassin.s: src/units/Fantassin.cpp.s

.PHONY : src/units/Fantassin.s

# target to generate assembly for a file
src/units/Fantassin.cpp.s:
	$(MAKE) -f CMakeFiles/AgeOfWar.dir/build.make CMakeFiles/AgeOfWar.dir/src/units/Fantassin.cpp.s
.PHONY : src/units/Fantassin.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... AgeOfWar"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/game/Board.o"
	@echo "... src/game/Board.i"
	@echo "... src/game/Board.s"
	@echo "... src/game/BuyingManager.o"
	@echo "... src/game/BuyingManager.i"
	@echo "... src/game/BuyingManager.s"
	@echo "... src/game/GameLogger.o"
	@echo "... src/game/GameLogger.i"
	@echo "... src/game/GameLogger.s"
	@echo "... src/game/GameManager.o"
	@echo "... src/game/GameManager.i"
	@echo "... src/game/GameManager.s"
	@echo "... src/players/ComputerPlayer.o"
	@echo "... src/players/ComputerPlayer.i"
	@echo "... src/players/ComputerPlayer.s"
	@echo "... src/players/HumanPlayer.o"
	@echo "... src/players/HumanPlayer.i"
	@echo "... src/players/HumanPlayer.s"
	@echo "... src/players/IPlayer.o"
	@echo "... src/players/IPlayer.i"
	@echo "... src/players/IPlayer.s"
	@echo "... src/units/Archer.o"
	@echo "... src/units/Archer.i"
	@echo "... src/units/Archer.s"
	@echo "... src/units/Catapult.o"
	@echo "... src/units/Catapult.i"
	@echo "... src/units/Catapult.s"
	@echo "... src/units/Fantassin.o"
	@echo "... src/units/Fantassin.i"
	@echo "... src/units/Fantassin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

